from __future__ import annotations

import json

from bagent.models import Agent, Guardrails, Pipeline


def generate_entry_sh(
    pipeline: Pipeline,
    agents: list[Agent],
    step_guardrails: list[Guardrails],
) -> str:
    """Generate the entry.sh bash script for the pipeline."""
    agent_map = {a.name: a for a in agents}

    lines: list[str] = []
    w = lines.append

    # --- Preamble ---
    w("#!/usr/bin/env bash")
    w("set -euo pipefail")
    w("")
    w(f'PIPELINE_NAME="{pipeline.name}"')
    w('SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"')
    w("")
    w("# --- Argument Parsing ---")
    w('TASK=""')
    w("while [[ $# -gt 0 ]]; do")
    w("  case $1 in")
    w("    -f|--file)")
    w('      if [[ ! -f "$2" ]]; then')
    w('        echo "Error: File not found: $2" >&2')
    w("        exit 1")
    w("      fi")
    w('      TASK=$(cat "$2")')
    w("      shift 2")
    w("      ;;")
    w("    -h|--help)")
    w('      echo "Usage: $0 [-f|--file <task_file>] [<task_string>]"')
    w('      echo ""')
    w(f'      echo "Pipeline: {pipeline.name}"')
    w(f'      echo "Description: {pipeline.description}"')
    w('      echo ""')
    w('      echo "Options:"')
    w('      echo "  -f, --file    Read task from a file"')
    w('      echo "  -h, --help    Show this help message"')
    w("      exit 0")
    w("      ;;")
    w("    *)")
    w('      TASK="$1"')
    w("      shift")
    w("      ;;")
    w("  esac")
    w("done")
    w("")
    w('if [[ -z "$TASK" ]]; then')
    w('  echo "Error: No task provided. Use -f <file> or pass a task string." >&2')
    w("  exit 1")
    w("fi")
    w("")

    # --- Run ID and directories ---
    w("# --- Run Setup ---")
    w('RUN_ID="$(date +%Y%m%d_%H%M%S)_$$"')
    w('RUN_DIR="$SCRIPT_DIR/runs/$RUN_ID"')
    w('mkdir -p "$RUN_DIR"')
    w("")

    # --- State file init ---
    w('# --- State Initialization ---')
    w('STATE_FILE="$RUN_DIR/state.json"')
    w('cat > "$STATE_FILE" <<STATEEOF')
    w("{")
    w(f'  "pipeline": "{pipeline.name}",')
    w('  "run_id": "$RUN_ID",')
    w('  "status": "running",')
    w('  "steps": []')
    w("}")
    w("STATEEOF")
    w("")

    # --- Preflight Checks ---
    w("# --- Preflight Checks ---")
    w("preflight_ok=true")
    w('for cmd in claude python3 jq; do')
    w('  if ! command -v "$cmd" &>/dev/null; then')
    w('    echo "Error: Required command not found: $cmd" >&2')
    w("    preflight_ok=false")
    w("  fi")
    w("done")
    w('if [[ "$preflight_ok" != "true" ]]; then')
    w("  exit 1")
    w("fi")
    w("")

    # --- update_state helper ---
    w("# --- State Update Helper ---")
    w("update_state() {")
    w('  local step_name="$1"')
    w('  local step_status="$2"')
    w('  local step_file="${3:-}"')
    w('  local tmp_state')
    w('  tmp_state=$(mktemp)')
    w('  jq --arg name "$step_name" \\')
    w('     --arg status "$step_status" \\')
    w('     --arg file "$step_file" \\')
    w("     '.steps += [{\"name\": $name, \"status\": $status, \"output_file\": $file}]' \\")
    w('     "$STATE_FILE" > "$tmp_state" && mv "$tmp_state" "$STATE_FILE"')
    w("}")
    w("")

    # --- run_step function ---
    w("# --- Step Runner ---")
    w("run_step() {")
    w('  local step_num="$1"')
    w('  local step_name="$2"')
    w('  local agent_file="$3"')
    w('  local schema_file="$4"')
    w('  local model="$5"')
    w('  local max_retries="$6"')
    w('  local timeout_secs="$7"')
    w('  local max_tokens="$8"')
    w('  local allowed_tools="$9"')
    w('  local banned_patterns="${10}"')
    w('  local task_input="${11}"')
    w('  local prev_output="${12:-}"')
    w("")
    w('  local output_file="$RUN_DIR/step_${step_num}_${step_name}.json"')
    w('  local agent_prompt')
    w('  agent_prompt=$(cat "$agent_file")')
    w("")
    w("  # Build full prompt")
    w('  local full_prompt="$agent_prompt"')
    w('  full_prompt+=$\'\\n\\n<task>\\n\'')
    w('  full_prompt+="$task_input"')
    w('  full_prompt+=$\'\\n</task>\'')
    w("")
    w('  if [[ -n "$prev_output" && -f "$prev_output" ]]; then')
    w('    full_prompt+=$\'\\n\\n<previous_step_output>\\n\'')
    w('    full_prompt+="$(cat "$prev_output")"')
    w('    full_prompt+=$\'\\n</previous_step_output>\'')
    w("  fi")
    w("")
    w('  if [[ -n "$schema_file" && -f "$schema_file" ]]; then')
    w('    full_prompt+=$\'\\n\\nYou MUST respond with valid JSON matching this schema:\\n\'')
    w('    full_prompt+="$(cat "$schema_file")"')
    w('    full_prompt+=$\'\\nRespond ONLY with the JSON object, no other text.\'')
    w("  fi")
    w("")
    w('  echo "--- Step $step_num: $step_name ---"')
    w("")
    w("  local attempt=0")
    w("  local success=false")
    w("")
    w("  while [[ $attempt -lt $max_retries ]]; do")
    w("    attempt=$((attempt + 1))")
    w('    echo "  Attempt $attempt/$max_retries..."')
    w("")
    w("    # Build claude command")
    w('    local claude_cmd=(claude -p --output-format json)')
    w('    if [[ -n "$model" ]]; then')
    w('      claude_cmd+=(--model "$model")')
    w("    fi")
    w('    if [[ -n "$max_tokens" && "$max_tokens" != "0" ]]; then')
    w('      claude_cmd+=(--max-tokens "$max_tokens")')
    w("    fi")
    w('    if [[ -n "$allowed_tools" ]]; then')
    w("      IFS=',' read -ra tools_arr <<< \"$allowed_tools\"")
    w('      for tool in "${tools_arr[@]}"; do')
    w('        claude_cmd+=(--allowedTools "$tool")')
    w("      done")
    w("    fi")
    w("")
    w("    # Run claude with optional timeout")
    w('    local raw_output=""')
    w('    local raw_file="$RUN_DIR/step_${step_num}_${step_name}_attempt_${attempt}_raw.json"')
    w("")
    w('    if [[ -n "$timeout_secs" && "$timeout_secs" != "0" ]]; then')
    w('      raw_output=$(timeout "$timeout_secs" "${claude_cmd[@]}" <<< "$full_prompt" 2>/dev/null) || {')
    w('        echo "  Attempt $attempt timed out or failed." >&2')
    w("        continue")
    w("      }")
    w("    else")
    w('      raw_output=$("${claude_cmd[@]}" <<< "$full_prompt" 2>/dev/null) || {')
    w('        echo "  Attempt $attempt failed." >&2')
    w("        continue")
    w("      }")
    w("    fi")
    w("")
    w("    # Extract the result text from claude's JSON output")
    w('    local result_text')
    w('    result_text=$(echo "$raw_output" | jq -r \'.result // empty\') || result_text="$raw_output"')
    w('    echo "$result_text" > "$raw_file"')
    w("")
    w("    # Check banned patterns")
    w('    if [[ -n "$banned_patterns" ]]; then')
    w("      local banned_found=false")
    w("      IFS='|' read -ra banned_arr <<< \"$banned_patterns\"")
    w('      for pattern in "${banned_arr[@]}"; do')
    w('        if echo "$result_text" | grep -qF "$pattern"; then')
    w('          echo "  Banned pattern found: $pattern" >&2')
    w("          banned_found=true")
    w("          break")
    w("        fi")
    w("      done")
    w('      if [[ "$banned_found" == "true" ]]; then')
    w("        full_prompt+=$'\\n\\nYour previous response contained a banned pattern. Please revise.'")
    w("        continue")
    w("      fi")
    w("    fi")
    w("")
    w("    # Validate against schema if present")
    w('    if [[ -n "$schema_file" && -f "$schema_file" ]]; then')
    w('      local validation_error')
    w('      validation_error=$(echo "$result_text" | python3 "$SCRIPT_DIR/validate_schema.py" "$schema_file" 2>&1) || {')
    w('        echo "  Schema validation failed: $validation_error" >&2')
    w("        full_prompt+=$'\\n\\nYour previous response failed schema validation with error: '")
    w('        full_prompt+="$validation_error"')
    w("        full_prompt+=$'\\nPlease fix and respond with valid JSON only.'")
    w("        continue")
    w("      }")
    w("    fi")
    w("")
    w("    # Success")
    w('    echo "$result_text" > "$output_file"')
    w("    success=true")
    w("    break")
    w("  done")
    w("")
    w('  if [[ "$success" == "true" ]]; then')
    w('    echo "  Step $step_name completed successfully."')
    w('    update_state "$step_name" "success" "$output_file"')
    w('    echo "$output_file"')
    w("  else")
    w('    echo "  Step $step_name FAILED after $max_retries attempts." >&2')
    w('    update_state "$step_name" "failed" ""')
    w("")
    w("    # Mark pipeline as failed")
    w('    local tmp_state')
    w('    tmp_state=$(mktemp)')
    w('    jq \'.status = "failed"\' "$STATE_FILE" > "$tmp_state" && mv "$tmp_state" "$STATE_FILE"')
    w("    exit 1")
    w("  fi")
    w("}")
    w("")

    # --- Step Calls ---
    w("# --- Pipeline Steps ---")
    w('PREV_OUTPUT=""')
    w("")

    for i, step in enumerate(pipeline.steps):
        agent = agent_map[step.agent]
        guardrails = step_guardrails[i]
        step_num = f"{i + 1:02d}"

        has_schema = agent.schema is not None
        schema_file_ref = f'"$SCRIPT_DIR/schemas/{agent.name}.json"' if has_schema else '""'
        tools_csv = ",".join(agent.tools) if agent.tools else ""
        banned_pipe = "|".join(guardrails.banned_patterns) if guardrails.banned_patterns else ""
        max_tokens_str = str(guardrails.max_tokens) if guardrails.max_tokens else "0"
        timeout_str = str(guardrails.timeout) if guardrails.timeout else "0"

        w(f'PREV_OUTPUT=$(run_step "{step_num}" "{agent.name}" \\')
        w(f'  "$SCRIPT_DIR/agents/{agent.name}.md" \\')
        w(f"  {schema_file_ref} \\")
        w(f'  "{agent.model}" \\')
        w(f'  "{guardrails.max_retries}" \\')
        w(f'  "{timeout_str}" \\')
        w(f'  "{max_tokens_str}" \\')
        w(f'  "{tools_csv}" \\')
        w(f'  "{_bash_escape(banned_pipe)}" \\')
        w(f'  "$TASK" \\')
        w(f'  "$PREV_OUTPUT")')
        w("")

    # --- Completion ---
    w("# --- Pipeline Complete ---")
    w('tmp_state=$(mktemp)')
    w('jq \'.status = "completed"\' "$STATE_FILE" > "$tmp_state" && mv "$tmp_state" "$STATE_FILE"')
    w("")
    w('echo ""')
    w('echo "=== Pipeline \'$PIPELINE_NAME\' completed successfully ==="')
    w('echo "Run ID: $RUN_ID"')
    w('echo "Output: $RUN_DIR"')

    return "\n".join(lines) + "\n"


def _bash_escape(s: str) -> str:
    """Escape characters problematic in bash double-quoted strings."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
